name: ci

on:
  push:
    branches:
      - 'main'
      - 'master'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./TextDb/Dockerfile
          push: true
          tags: ghcr.io/darknamer/textdb:latest

      - uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster.
      # - uses: Azure/aks-set-context@v1
      #   with:
      #     creds: "${{ secrets.AZURE_CREDENTIALS }}"
      #     cluster-name: contoso
      #     resource-group: contoso-rg
      # - uses: Azure/k8s-create-secret@v1.1
      #   with:
      #     namespace: ${{ env.NAMESPACE  }}
      #     container-registry-url: contoso.azurecr.io
      #     container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      #     secret-name: demo-k8s-secret
      # - uses: azure/k8s-bake@v2
      #   with:
      #     renderEngine: "helm"
      #     helmChart: "./aks-helloworld/"
      #     overrideFiles: "./aks-helloworld/values-override.yaml"
      #     helm-version: "latest"
      #   id: bake
      # - uses: Azure/k8s-deploy@v1.2
      #   with:
      #     action: deploy
      #     manifests: ${{ steps.bake.outputs.manifestsBundle }}
      #     images: |
      #       contoso.azurecr.io/k8sdemo:${{ github.sha }}
      #     imagepullsecrets: |
      #       demo-k8s-secret